project:
  type: website

website:
  title: "ggplotly workshop"
  navbar:
    background: "#88398A"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tutorial.qmd

format:
  html:
    theme:
      - theme-dark.scss
    css: 
      - styles.css
      - all.min.css
    toc: true
    fontawesome: true

editor: visual

