project:
  type: website

website:
  title: "ggplotly_workshop_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tutorial.qmd

format:
  html:
    theme:
      dark: [cosmo, theme-dark.css]
    css: styles.css
    toc: true
    fontawesome: true

editor: visual

